- hosts: all
  tasks:
    - name: Download Deb Package
      ansible.builtin.get_url:
        url: https://github.com/KhaledEmaraDev/scsm-ansible/raw/main/scsm-7.12.0.8000-Ubuntu22_x64.deb
        dest: /tmp/scsm-7.12.0.8000-Ubuntu22_x64.deb
        mode: '0777'

    - name: Install Dependencies
      become: yes
      apt:
        pkg:
          - libc6-i386
          - auditd

    - name: Install Deb Package
      become: yes
      shell: "dpkg -i /tmp/scsm-7.12.0.8000-Ubuntu22_x64.deb"

    - name: Enable Agent
      become: yes
      shell: "update-rc.d scsm start 20 3 5 . stop 20 0 1 2 6 ."

    - name: Configure Agent Host
      ansible.builtin.replace:
        path: /opt/logrhythm/scsm/config/scsm.ini
        regexp: '^Host=CHANGE_THIS$'
        replace: 'Host=158.101.230.147'

    - name: Get Private IP
      become: yes
      shell: "ip route get 1.2.3.4 | awk '{print $7}' | tr -d '\n'"
      register: ip_content

    - name: Configure Agent ClientAddress
      ansible.builtin.replace:
        path: /opt/logrhythm/scsm/config/scsm.ini
        regexp: '^ClientAddress=0$'
        replace: 'ClientAddress={{ip_content.stdout}}'

    - name: Configure Agent ClientPort
      ansible.builtin.replace:
        path: /opt/logrhythm/scsm/config/scsm.ini
        regexp: '^ClientPort=0$'
        replace: 'ClientPort=3333'

    - name: Restart Service
      systemd:
        state: started
        name: scsm
        enabled: true
